apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-integration-configuration-service_fintlabs_no
      fintlabs.no/org-id: fintlabs.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"

    target:
      kind: Application
      name: fint-flyt-integration-configuration-service
