apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-intgr-conf-service_nfk_no
      fintlabs.no/org-id: nfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "nfk.no"

    target:
      kind: Application
      name: fint-flyt-intgr-conf-service
